stages:
  - build

Conan:
  stage: build
  before_script:
      - add-apt-repository universe && apt-get update
      - apt-get install python3-pip
      - pip install conan
      - source ~/.profile
  script:  
    - mkdir build && cd build
    - conan profile new goodok-profile --detect
    - conan profile update settings.compiler.version=8 goodok-profile
    - conan install .. --profile goodok-profile