#image: registry.gitlab.com/goodok-chat/messaging-framework:latest
image: kstmorozov/client-dekstop:latest
stages:
  - build
variables:
  CONAN_SYSREQUIRES_MODE: enabled
Build:
  stage: build
  before_script:
    - mkdir build && cd build
    - conan profile new goodok-profile --detect
    - conan profile update settings.compiler.version=9.3 goodok-profile
    - conan profile update settings.compiler.libcxx=libstdc++11 goodok-profile
#    - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  script:
    - conan install .. --build missing --profile goodok-profile
#    - conan install -s build_type=Release .. --build missing --profile goodok-profile
    - cmake ..
    - cmake --build .

