language: cpp

matrix:
  include:
    - os: linux
      dist: focal
      addons:
        apt:
          packages:
            - g++-10
            - graphviz
            - doxygen
            - python3
            - python3-pip
            - cmake
            - wget
      env:
        - MATRIX_EVAL="CXX=g++-10"
        - BUILD_DIR=build
        - APP_NAME=gateway
      before_install:
        - eval "${MATRIX_EVAL}"
      before_script:
#        - apt-get install g++-10
        - pip install --upgrade pip
        - pip install conan
        - source ~/.profile
      cache:
        directories:
          - /home/travis/.conan
      script:
        - mkdir -p ${BUILD_DIR}  && cd ${BUILD_DIR} && mkdir -p proto
        - sudo apt-get install -y qt5-default
        - sudo apt-get install -y libgl1-mesa-dev libx11-dev libx11-xcb-dev libxcb-dri3-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-render-util0-dev libxcb-render0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-util-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-xkb-dev xorg-dev
        - conan profile new goodok-profile --detect --force
        - conan profile update settings.compiler.version=10 goodok-profile
        - conan profile update settings.compiler.libcxx=libstdc++11 goodok-profile
        - conan install -s build_type=Release .. --profile goodok-profile
        - wget https://github.com/k-morozov/messaging-framework/releases/download/0.1.6-Linux/Messaging-framework-0.1.3-Linux.deb
        - sudo apt-get install ./Messaging-framework-0.1.3-Linux.deb
        - cmake ..
        - cmake --build . -- -j 4
        - cmake --build . --target package

      before_deploy:
        - git config --local user.name "k-morozov"
        - git config --local user.email "morozov-kst@yandex.ru"
        - git tag 0.8.$TRAVIS_BUILD_NUMBER-Linux
      deploy:
        - provider: releases
          api_key: $DEKSTOP_TOKEN
          file: goodok-dekstop-0.8.$TRAVIS_BUILD_NUMBER-Linux.deb
          skip_cleanup: true
          on:
            branch: master
